# Generated by Django 4.1.2 on 2022-10-30 09:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='content_preview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
