# Generated by Django 4.1 on 2022-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0002_aktualnosci_content_preview_alter_aktualnosci_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
