# Generated by Django 4.1.2 on 2022-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0003_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
