# Generated by Django 4.1.2 on 2022-11-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0006_remove_aktualnosci_downloads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('wydarzenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wydarzenie_photos', to='freskbackend.aktualnosci')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('wydarzenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wydarzenie_files', to='freskbackend.aktualnosci')),
            ],
        ),
    ]
