# Generated by Django 4.1 on 2022-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0007_photos_downloadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='content',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='content_preview',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
