# Generated by Django 4.1 on 2022-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0011_alter_aktualnosci_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conForm', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
