# Generated by Django 4.1 on 2022-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0012_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='file_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
