# Generated by Django 4.1.2 on 2022-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0013_downloadfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
